<?xml version="1.0" encoding="utf-8"?><Database Name="SoLienLacDT" Class="DataClasses1DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=.;Initial Catalog=SoLienLacDT;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="SoLienLacDTConnectionString1" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Admin" Member="Admins">
    <Type Name="Admin">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TaiKhoan" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Password" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="TenAdmin" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="PasswordEmail" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.ThongBaoChung" Member="ThongBaoChungs">
    <Type Name="ThongBaoChung">
      <Column Name="MaTB" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TieuDe" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="NoiDung" Type="System.String" DbType="NText NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="NgayDang" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.ChiTietHocPhi" Member="ChiTietHocPhis">
    <Type Name="ChiTietHocPhi">
      <Column Name="MaMon" Type="System.String" DbType="VarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TCHP" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="PhiTL" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="HocPhi" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="SoTienPhaiDong" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Association Name="MonHoc_ChiTietHocPhi" Member="MonHoc" ThisKey="MaMon" OtherKey="MaMon" Type="MonHoc" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Diem" Member="Diems">
    <Type Name="Diem">
      <Column Name="IDDiem" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="MaSV" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="DiemTBTichLuy" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="DiemTBHK" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="SoTinChiDat" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SoTinChiTL" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NamHoc" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="HocKy" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Diem_DiemCT" Member="DiemCTs" ThisKey="IDDiem" OtherKey="IDDiem" Type="DiemCT" />
      <Association Name="SinhVien_Diem" Member="SinhVien" ThisKey="MaSV" OtherKey="MaSV" Type="SinhVien" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.DiemCT" Member="DiemCTs">
    <Type Name="DiemCT">
      <Column Name="IDDiemCT" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="IDDiem" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MaMon" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="NamHoc" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="DiemGK" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="DiemCK" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="DiemTBM" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="HocKy" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="KQ" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="Diem_DiemCT" Member="Diem" ThisKey="IDDiem" OtherKey="IDDiem" Type="Diem" IsForeignKey="true" />
      <Association Name="MonHoc_DiemCT" Member="MonHoc" ThisKey="MaMon" OtherKey="MaMon" Type="MonHoc" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Don" Member="Dons">
    <Type Name="Don">
      <Column Name="STT" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="MaSV" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="TenSV" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="LiDo" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="FileDon" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="NgayDang" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="TrangThai" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.GiangVien" Member="GiangViens">
    <Type Name="GiangVien">
      <Column Name="MaGV" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TenGV" Type="System.String" DbType="NChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Password" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="GiangVien_GiangVien_Nganh" Member="GiangVien_Nganhs" ThisKey="MaGV" OtherKey="MaGV" Type="GiangVien_Nganh" />
      <Association Name="GiangVien_GV_LM" Member="GV_LMs" ThisKey="MaGV" OtherKey="MaGV" Type="GV_LM" />
      <Association Name="GiangVien_GV_Mon" Member="GV_Mons" ThisKey="MaGV" OtherKey="MaGV" Type="GV_Mon" />
      <Association Name="GiangVien_Lop" Member="Lops" ThisKey="MaGV" OtherKey="MaGV" Type="Lop" />
      <Association Name="GiangVien_ThongBao" Member="ThongBaos" ThisKey="MaGV" OtherKey="MaGV" Type="ThongBao" />
    </Type>
  </Table>
  <Table Name="dbo.GiangVien_Nganh" Member="GiangVien_Nganhs">
    <Type Name="GiangVien_Nganh">
      <Column Name="Stt" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="MaGV" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="MaNganh" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="GiangVien_GiangVien_Nganh" Member="GiangVien" ThisKey="MaGV" OtherKey="MaGV" Type="GiangVien" IsForeignKey="true" />
      <Association Name="Nganh_GiangVien_Nganh" Member="Nganh" ThisKey="MaNganh" OtherKey="MaNganh" Type="Nganh" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.GV_LM" Member="GV_LMs">
    <Type Name="GV_LM">
      <Column Name="STT" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="MaLM" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="MaGV" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="GiangVien_GV_LM" Member="GiangVien" ThisKey="MaGV" OtherKey="MaGV" Type="GiangVien" IsForeignKey="true" />
      <Association Name="LopMon_GV_LM" Member="LopMon" ThisKey="MaLM" OtherKey="MaLM" Type="LopMon" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.GV_Mon" Member="GV_Mons">
    <Type Name="GV_Mon">
      <Column Name="MaGV" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="MaMon" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Association Name="GiangVien_GV_Mon" Member="GiangVien" ThisKey="MaGV" OtherKey="MaGV" Type="GiangVien" IsForeignKey="true" />
      <Association Name="MonHoc_GV_Mon" Member="MonHoc" ThisKey="MaMon" OtherKey="MaMon" Type="MonHoc" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.LichThi" Member="LichThis">
    <Type Name="LichThi">
      <Column Name="IDLichThi" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="MaMon" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="MaSV" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="TenMon" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="NhomThi" Type="System.String" DbType="VarChar(5) NOT NULL" CanBeNull="false" />
      <Column Name="NgayThi" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="GioBD" Type="System.TimeSpan" DbType="Time NOT NULL" CanBeNull="false" />
      <Column Name="SoPhut" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Phong" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="GhiChu" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="NamHoc" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="HocKy" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="MonHoc_LichThi" Member="MonHoc" ThisKey="MaMon" OtherKey="MaMon" Type="MonHoc" IsForeignKey="true" />
      <Association Name="SinhVien_LichThi" Member="SinhVien" ThisKey="MaSV" OtherKey="MaSV" Type="SinhVien" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.LoaiDK" Member="LoaiDKs">
    <Type Name="LoaiDK">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TenLoaiDK" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Lop" Member="Lops">
    <Type Name="Lop">
      <Column Name="Malop" Type="System.String" DbType="VarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MaGV" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="Lop_SV_LOP" Member="SV_LOPs" ThisKey="Malop" OtherKey="Malop" Type="SV_LOP" />
      <Association Name="GiangVien_Lop" Member="GiangVien" ThisKey="MaGV" OtherKey="MaGV" Type="GiangVien" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.LopMon" Member="LopMons">
    <Type Name="LopMon">
      <Column Name="MaLM" Type="System.String" DbType="VarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Lop" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="MaMon" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Association Name="LopMon_GV_LM" Member="GV_LMs" ThisKey="MaLM" OtherKey="MaLM" Type="GV_LM" />
      <Association Name="LopMon_SinhVien_LopMon" Member="SinhVien_LopMons" ThisKey="MaLM" OtherKey="MaLM" Type="SinhVien_LopMon" />
      <Association Name="LopMon_ThongBao" Member="ThongBaos" ThisKey="MaLM" OtherKey="MaLM" Type="ThongBao" />
      <Association Name="MonHoc_LopMon" Member="MonHoc" ThisKey="MaMon" OtherKey="MaMon" Type="MonHoc" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.MonHoc" Member="MonHocs">
    <Type Name="MonHoc">
      <Column Name="MaMon" Type="System.String" DbType="VarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TenMon" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Sotinchi" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MaMonTienQuyet" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Association Name="MonHoc_ChiTietHocPhi" Member="ChiTietHocPhi" ThisKey="MaMon" OtherKey="MaMon" Type="ChiTietHocPhi" Cardinality="One" />
      <Association Name="MonHoc_DiemCT" Member="DiemCTs" ThisKey="MaMon" OtherKey="MaMon" Type="DiemCT" />
      <Association Name="MonHoc_GV_Mon" Member="GV_Mons" ThisKey="MaMon" OtherKey="MaMon" Type="GV_Mon" />
      <Association Name="MonHoc_LichThi" Member="LichThis" ThisKey="MaMon" OtherKey="MaMon" Type="LichThi" />
      <Association Name="MonHoc_LopMon" Member="LopMons" ThisKey="MaMon" OtherKey="MaMon" Type="LopMon" />
      <Association Name="MonHoc_Nganh_Mon" Member="Nganh_Mons" ThisKey="MaMon" OtherKey="MaMon" Type="Nganh_Mon" />
      <Association Name="MonHoc_SV_MON" Member="SV_MONs" ThisKey="MaMon" OtherKey="MaMon" Type="SV_MON" />
      <Association Name="MonHoc_ThoiKhoaBieu" Member="ThoiKhoaBieus" ThisKey="MaMon" OtherKey="MaMon" Type="ThoiKhoaBieu" />
    </Type>
  </Table>
  <Table Name="dbo.Nganh" Member="Nganhs">
    <Type Name="Nganh">
      <Column Name="MaNganh" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TenNganh" Type="System.String" DbType="NChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="TongTC" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Nganh_GiangVien_Nganh" Member="GiangVien_Nganhs" ThisKey="MaNganh" OtherKey="MaNganh" Type="GiangVien_Nganh" />
      <Association Name="Nganh_Nganh_Mon" Member="Nganh_Mons" ThisKey="MaNganh" OtherKey="MaNganh" Type="Nganh_Mon" />
      <Association Name="Nganh_SinhVien_Nganh" Member="SinhVien_Nganhs" ThisKey="MaNganh" OtherKey="MaNganh" Type="SinhVien_Nganh" />
    </Type>
  </Table>
  <Table Name="dbo.Nganh_Mon" Member="Nganh_Mons">
    <Type Name="Nganh_Mon">
      <Column Name="MaNganh" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="MaMon" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Association Name="MonHoc_Nganh_Mon" Member="MonHoc" ThisKey="MaMon" OtherKey="MaMon" Type="MonHoc" IsForeignKey="true" />
      <Association Name="Nganh_Nganh_Mon" Member="Nganh" ThisKey="MaNganh" OtherKey="MaNganh" Type="Nganh" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.PH" Member="PHs">
    <Type Name="PH">
      <Column Name="MaPH" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TenPH" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="SDTPH" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Association Name="PH_SinhVien" Member="SinhViens" ThisKey="MaPH" OtherKey="MaPH" Type="SinhVien" />
    </Type>
  </Table>
  <Table Name="dbo.SinhVien" Member="SinhViens">
    <Type Name="SinhVien">
      <Column Name="MaSV" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TenSV" Type="System.String" DbType="NChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="GioiTinh" Type="System.String" DbType="NChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="Diachi" Type="System.String" DbType="NText NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="Email" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="SDT" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="NgaySinh" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Password" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="MaPH" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="SinhVien_Diem" Member="Diems" ThisKey="MaSV" OtherKey="MaSV" Type="Diem" />
      <Association Name="SinhVien_LichThi" Member="LichThis" ThisKey="MaSV" OtherKey="MaSV" Type="LichThi" />
      <Association Name="SinhVien_SinhVien_LopMon" Member="SinhVien_LopMons" ThisKey="MaSV" OtherKey="MaSV" Type="SinhVien_LopMon" />
      <Association Name="SinhVien_SinhVien_Nganh" Member="SinhVien_Nganhs" ThisKey="MaSV" OtherKey="MaSV" Type="SinhVien_Nganh" />
      <Association Name="SinhVien_SV_LOP" Member="SV_LOPs" ThisKey="MaSV" OtherKey="MaSV" Type="SV_LOP" />
      <Association Name="SinhVien_SV_MON" Member="SV_MONs" ThisKey="MaSV" OtherKey="MaSV" Type="SV_MON" />
      <Association Name="PH_SinhVien" Member="PH" ThisKey="MaPH" OtherKey="MaPH" Type="PH" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.SinhVien_LopMon" Member="SinhVien_LopMons">
    <Type Name="SinhVien_LopMon">
      <Column Name="ST" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="MaSV" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="MaLM" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Association Name="LopMon_SinhVien_LopMon" Member="LopMon" ThisKey="MaLM" OtherKey="MaLM" Type="LopMon" IsForeignKey="true" />
      <Association Name="SinhVien_SinhVien_LopMon" Member="SinhVien" ThisKey="MaSV" OtherKey="MaSV" Type="SinhVien" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.SinhVien_Nganh" Member="SinhVien_Nganhs">
    <Type Name="SinhVien_Nganh">
      <Column Name="MaSV" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="MaNganh" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="Nganh_SinhVien_Nganh" Member="Nganh" ThisKey="MaNganh" OtherKey="MaNganh" Type="Nganh" IsForeignKey="true" />
      <Association Name="SinhVien_SinhVien_Nganh" Member="SinhVien" ThisKey="MaSV" OtherKey="MaSV" Type="SinhVien" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.SV_LOP" Member="SV_LOPs">
    <Type Name="SV_LOP">
      <Column Name="STT" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Malop" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="MaSV" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="Lop_SV_LOP" Member="Lop" ThisKey="Malop" OtherKey="Malop" Type="Lop" IsForeignKey="true" />
      <Association Name="SinhVien_SV_LOP" Member="SinhVien" ThisKey="MaSV" OtherKey="MaSV" Type="SinhVien" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.SV_MON" Member="SV_MONs">
    <Type Name="SV_MON">
      <Column Name="STT" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="MaSV" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="MaMon" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="DaHoc" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="MaMonTienquyet" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="MonHoc_SV_MON" Member="MonHoc" ThisKey="MaMon" OtherKey="MaMon" Type="MonHoc" IsForeignKey="true" />
      <Association Name="SinhVien_SV_MON" Member="SinhVien" ThisKey="MaSV" OtherKey="MaSV" Type="SinhVien" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.ThoiKhoaBieu" Member="ThoiKhoaBieus">
    <Type Name="ThoiKhoaBieu">
      <Column Name="IDTKB" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="MaMon" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="TenMon" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="MaGV" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Phong" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="TietBD" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Thu" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TH" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ST" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ThoiGianBD" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="HocKy" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="MaLM" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="ThoiGianKT" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="TongNgayHoc" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="MonHoc_ThoiKhoaBieu" Member="MonHoc" ThisKey="MaMon" OtherKey="MaMon" Type="MonHoc" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.ThongBao" Member="ThongBaos">
    <Type Name="ThongBao">
      <Column Name="IDTB" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="MaGV" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="NoiDung" Type="System.String" DbType="Text NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="NgayDang" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="MaLop" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="MaLM" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="MaSV" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="GiangVien_ThongBao" Member="GiangVien" ThisKey="MaGV" OtherKey="MaGV" Type="GiangVien" IsForeignKey="true" />
      <Association Name="LopMon_ThongBao" Member="LopMon" ThisKey="MaLM" OtherKey="MaLM" Type="LopMon" IsForeignKey="true" />
    </Type>
  </Table>
</Database>