//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoLienLacDienTu.Models.Entry
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTietHocPhi
    {
        public string MaMon { get; set; }
        public Nullable<double> TCHP { get; set; }
        public Nullable<int> PhiTL { get; set; }
        public Nullable<long> HocPhi { get; set; }
        public Nullable<long> SoTienPhaiDong { get; set; }
    
        public virtual MonHoc MonHoc { get; set; }
    }
}
