//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoLienLacDienTu.Models.Entry
{
    using System;
    using System.Collections.Generic;
    
    public partial class DiemCT
    {
        public int IDDiemCT { get; set; }
        public Nullable<int> IDDiem { get; set; }
        public string MaMon { get; set; }
        public string NamHoc { get; set; }
        public Nullable<double> DiemGK { get; set; }
        public Nullable<double> DiemCK { get; set; }
        public Nullable<double> DiemTBM { get; set; }
        public int HocKy { get; set; }
        public Nullable<bool> KQ { get; set; }
    
        public virtual Diem Diem { get; set; }
        public virtual MonHoc MonHoc { get; set; }
    }
}
