//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoLienLacDienTu.Models.Entry
{
    using System;
    using System.Collections.Generic;
    
    public partial class Diem
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Diem()
        {
            this.DiemCTs = new HashSet<DiemCT>();
        }
    
        public int IDDiem { get; set; }
        public string MaSV { get; set; }
        public Nullable<double> DiemTBTichLuy { get; set; }
        public Nullable<double> DiemTBHK { get; set; }
        public Nullable<int> SoTinChiDat { get; set; }
        public Nullable<int> SoTinChiTL { get; set; }
        public string NamHoc { get; set; }
        public int HocKy { get; set; }
    
        public virtual SinhVien SinhVien { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DiemCT> DiemCTs { get; set; }
    }
}
