//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoLienLacDienTu.Models.Entry
{
    using System;
    using System.Collections.Generic;
    
    public partial class Don
    {
        public int STT { get; set; }
        public string MaSV { get; set; }
        public string TenSV { get; set; }
        public string LiDo { get; set; }
        public string FileDon { get; set; }
        public Nullable<System.DateTime> NgayDang { get; set; }
        public Nullable<int> TrangThai { get; set; }
    }
}
