//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoLienLacDienTu.Models.Entry
{
    using System;
    using System.Collections.Generic;
    
    public partial class LichThi
    {
        public int IDLichThi { get; set; }
        public string MaMon { get; set; }
        public string MaSV { get; set; }
        public string TenMon { get; set; }
        public string NhomThi { get; set; }
        public System.DateTime NgayThi { get; set; }
        public System.TimeSpan GioBD { get; set; }
        public int SoPhut { get; set; }
        public string Phong { get; set; }
        public string GhiChu { get; set; }
        public string NamHoc { get; set; }
        public int HocKy { get; set; }
    
        public virtual MonHoc MonHoc { get; set; }
        public virtual SinhVien SinhVien { get; set; }
    }
}
