//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoLienLacDienTu.Models.Entry
{
    using System;
    using System.Collections.Generic;
    
    public partial class ThoiKhoaBieu
    {
        public int IDTKB { get; set; }
        public string MaMon { get; set; }
        public string MaLM { get; set; }
        public string TenMon { get; set; }
        public string MaGV { get; set; }
        public string Phong { get; set; }
        public int TietBD { get; set; }
        public int Thu { get; set; }
        public Nullable<int> TH { get; set; }
        public int ST { get; set; }
        public Nullable<System.DateTime> ThoiGianBD { get; set; }
        public Nullable<System.DateTime> ThoiGianKT { get; set; }
        public Nullable<int> Nam { get; set; }
        public int HocKy { get; set; }
        public Nullable<int> TongNgayHoc { get; set; }
    
        public virtual MonHoc MonHoc { get; set; }
    }
}
