//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoLienLacDienTu.Models.Entry
{
    using System;
    using System.Collections.Generic;
    
    public partial class ThongBao
    {
        public int IDTB { get; set; }
        public string MaGV { get; set; }
        public string NoiDung { get; set; }
        public Nullable<System.DateTime> NgayDang { get; set; }
        public string MaLop { get; set; }
        public string MaLM { get; set; }
        public string MaSV { get; set; }
    
        public virtual GiangVien GiangVien { get; set; }
        public virtual LopMon LopMon { get; set; }
    }
}
